Refactor chroot-setup Makefile #46
 - Have all chroot-related targets check the mount status;
 - Get rid of `.ONESHELL` as it affects all targets (and thus
   masks errors in target shell commands);
 - Adopt target-specific variables where applicable;
 - Create and use `start-vnc.sh` and `stop-vnc.sh` for mate-desktop
   chroot;
 - Improve `chroot-status.sh`;
 - Update `build-tarball.sh` and the inside-chroot scripts accordignly.

diff --git a/chroot-setup/Makefile b/chroot-setup/Makefile
--- a/chroot-setup/Makefile
+++ b/chroot-setup/Makefile
@@ -9,147 +9,173 @@ include .env
 export
 
 SRC_DIR := ../src
+TEST_DIR := ../test
 SYNC_MASH := sync-mash  # timestamp-only file
 
-#: Umount all chroot-mounted points, removing any possible processes running
-#: in the chroot (mash uid is defined in `.env`).
-umount-chroot:
-	@for pid in $$(ps axu | awk '/^$(MASH_UID)/ {print $$2}'); do \
-		echo "Killing PID $$pid" \
-		;sudo kill $$pid \
-	;done
-	@if mount | grep -q "$(CHROOT)"; then ./umount-chroot.sh; fi
+
+#: Ensure a properly mounted chroot (20 < rc < 30) or exit with error.
+_ensure_chroot:
+	@./4make/chroot-status.sh > /dev/null && rc=$$? || rc=$$? \
+	;if [ "$$rc" -gt 20 -a "$$rc" -lt 30 ]; then \
+		exit 0 \
+	;fi \
+	;if [ "$$rc" -eq 0 ]; then \
+		./4make/chroot-status.sh || true \
+		;rc=7 \
+	;else \
+		echo 'IMPROPERLY mounted chroot found! Check status.' \
+		;./4make/chroot-status.sh || true \
+	;fi \
+	;exit $$rc
 
 
-#: Prepare a mount point with proper ownership and permissoins
-prep-chroot-dir:  umount-chroot
-	@if [ -e "$(CHROOT)" ]; then sudo rmdir "$(CHROOT)"; fi
-	@sudo mkdir -p "$(CHROOT)"
-	@sudo chown root:root "$(CHROOT)" && sudo chmod 775 "$(CHROOT)"
+#: Ensure no chroot directory is mounted (rc=0) or exit with error.
+_ensure_no_chroot:
+	@if ! ./4make/chroot-status.sh > /dev/null; then \
+		echo 'There is an ACTIVE chroot - check status.' \
+		;./4make/chroot-status.sh \
+		;exit 8 \
+	;fi
 
 
 #: Mount special paths into the soon-to-be-chrooted fs tree
-mount-chroot:  prep-chroot-dir
+mount-chroot:  _ensure_no_chroot
 	./mount-chroot.sh
 
 
-chroot-down:  umount-chroot
-
-
-$(FOCAL_HEADLESS_TAR):  prep-chroot-dir
-	@if [ -e "$(FOCAL_HEADLESS_TAR)" ]; then \
-		echo "$(FOCAL_HEADLESS_TAR) is up-to-date." \
-	;else \
-		./4make/build-tarball.sh headless \
-	;fi
-
-
-$(MATE_DESKTOP_TAR):  $(FOCAL_HEADLESS_TAR)  prep-chroot-dir
-	@if [ -e "$(MATE_DESKTOP_TAR)" ]; then \
-		echo "$(MATE_DESKTOP_TAR) is up-to-date." \
-	;else \
-		./4make/build-tarball.sh mate-desktop \
-	;fi
-
-
-clean-tarballs:
-	@for file in $(BUILD_DIR)/*gz; do \
-		echo "Removing $$file..." \
-		;rm -f "$$file" \
+#: Umount all chroot-mounted points, removing any possible processes running
+#: in the chroot (mash uid is defined in `.env`).
+umount-chroot:  _ensure_chroot
+	@for pid in $$(ps axu | awk '/^$(MASH_UID)/ {print $$2}'); do \
+		echo "Killing PID $$pid"; sudo kill $$pid \
 	;done
+	./umount-chroot.sh
 
 
-clean-mash-timestamp:
-	rm -f $(SYNC_MASH)
+#: Prepare a mount point with proper ownership and permissoins
+prep-chroot-dir:  _ensure_no_chroot
+	@# (First statement would fail if CHROOT directory is not empty.)
+	[ -e "$(CHROOT)" ] && sudo rmdir "$(CHROOT)" || true
+	sudo mkdir -p "$(CHROOT)"
+	sudo chown root:root "$(CHROOT)" && sudo chmod 775 "$(CHROOT)"
+	echo "$(CHROOT) created and set."
 
 
-clean-downloads:
-	rm -rf $(DOWNLOAD_DIR)
+chroot-down:  _ensure_chroot
+	make sync-downloads
+	make umount-chroot
 
 
-clean:  clean-tarballs
-
-
-clean-all: clean-tarballs clean-mash-timestamp clean-downloads
-
-
-.ONESHELL:
-headless-up: $(FOCAL_HEADLESS_TAR)  prep-chroot-dir
-	TARGET_NAME=headless
-	eval "TAR_FILE=$(TAR_FILE_TEMPLATE)"
+$(FOCAL_HEADLESS_TAR):
+	make prep-chroot-dir
 	./4make/ensure-free-mem.sh 2G
 	sudo mount -t tmpfs -o size=1G mash-ramdisk "${CHROOT}"
-	#sudo tar -xf "$$TAR_FILE" -g /dev/null -C "$(CHROOT)"
-	sudo tar -xf "$$TAR_FILE" -C "$(CHROOT)"
+	./4make/build-tarball.sh headless
+	sudo umount mash-ramdisk
+
+
+$(MATE_DESKTOP_TAR):  $(FOCAL_HEADLESS_TAR)
+	set -x; make prep-chroot-dir
+	./4make/ensure-free-mem.sh 6G
+	sudo mount -t tmpfs -o size=4G mash-ramdisk "${CHROOT}"
+	./4make/build-tarball.sh mate-desktop
+	sudo umount mash-ramdisk
+
+
+headless-up: TARGET_NAME := headless
+headless-up: TAR_FILE = $(TAR_FILE_TEMPLATE)
+headless-up: $(FOCAL_HEADLESS_TAR)  prep-chroot-dir
+	@echo "TAR_FILE=$(TAR_FILE)"
+	./4make/ensure-free-mem.sh 3G
+	sudo mount -t tmpfs -o size=2G mash-ramdisk "${CHROOT}"
+	sudo tar -xf "$(TAR_FILE)" -C "$(CHROOT)"
 	./mount-chroot.sh
 	./4make/copy-mash-in-chroot.sh
+	make sync-downloads
 	echo 'Now do something in the chroot ;)  e.g. sudo chroot $(CHROOT) bash'
 
 
 headless-down:  chroot-down
 
 
-.ONESHELL:
+mate-desktop-up: TARGET_NAME := mate-desktop
+mate-desktop-up: TAR_FILE = $(TAR_FILE_TEMPLATE)
 mate-desktop-up:  $(MATE_DESKTOP_TAR)  prep-chroot-dir
-	set -x
-	TARGET_NAME=mate-desktop
-	eval "TAR_FILE=$(TAR_FILE_TEMPLATE)"
-	echo "TAR_FILE=$$TAR_FILE"
+	echo "TAR_FILE=$(TAR_FILE)"
 	./4make/ensure-free-mem.sh 8G
 	sudo mount -t tmpfs -o size=6G mash-ramdisk "${CHROOT}"
-	#sudo tar -xzf "$(FOCAL_HEADLESS_TAR)" -g /dev/null -C "$(CHROOT)" || true
-	#sudo tar -xzf "$(FOCAL_HEADLESS_TAR)" -C "$(CHROOT)"
-	#sudo tar -xzf "$$TAR_FILE" -g /dev/null -C "$(CHROOT)" || true
 	sudo tar -xzf "$$TAR_FILE" -C "$(CHROOT)"
 	./mount-chroot.sh
 	./4make/copy-mash-in-chroot.sh
-	set +x
+	make sync-downloads
+	sudo chroot "$(CHROOT)" start-vnc.sh
 	echo 'Now do something in the chroot ;)  e.g. sudo chroot $(CHROOT) bash'
 
 
-mate-desktop-down:  chroot-down
+mate-desktop-down:  _ensure_chroot
+	@./4make/chroot-status.sh > /dev/null \
+	;if [ "$$?" != 22 ]; then \
+		"echo NOT found fully mounted *mate* chroot (rc=$?) - check chroot status" \
+		;exit 7 \
+	;fi
+	make sync-downloads
+	sudo chroot "$(CHROOT)" stop-vnc.sh
+	make chroot-down
 
 
 EXCLUDED := install.sh
-SOURCES := $(shell find "$(SRC_DIR)/" -name "*.*" -a ! -name $(EXCLUDED))
 CHROOT_LOCAL := $(CHROOT)/home/mash/.local
 RSYNC_OPTS := -rlptDv
-
-#: Sync local workspace mash code with the one installed in the chroot environment.
-#: Uses a timestamp file, so NOT .PHONY ;)
-sync-mash:  $(SOURCES)
-	@touch $(SYNC_MASH)
-	@sudo rsync $(RSYNC_OPTS) --del --exclude=$(EXCLUDED) $(SRC_DIR)/ $(CHROOT_LOCAL)/opt/mash/
+RSYNC_OPTS_4SYNC_MASH := -rlptDv --del --exclude=$(EXCLUDED)
 
 
 #: Sync local workspace mash code with the one installed in the chroot environment.
 #: (This one is .PHONY - always executed, unconditionally.)
-sync-mash-forced:
-	@sudo rsync $(RSYNC_OPTS) --del --exclude=$(EXCLUDED) $(SRC_DIR)/ $(CHROOT_LOCAL)/opt/mash/
+sync-mash:  _ensure_chroot
+	@sudo rsync $(RSYNC_OPTS_4SYNC_MASH) "$(SRC_DIR)/" "$(CHROOT_LOCAL)/opt/mash/"
+	@sudo rsync $(RSYNC_OPTS_4SYNC_MASH) "$(TEST_DIR)/" "$(CHROOT)/home/$(MASH_USER)/test/"
+	@sudo cp -p "$(SRC_DIR)/install.sh" "$(CHROOT)/home/$(MASH_USER)/install.sh"
+	@sudo chown "$(MASH_UID):$(MASH_UID)" \
+		"$(CHROOT_LOCAL)/opt/mash/" \
+		"$(CHROOT)/home/$(MASH_USER)/test/" \
+		"$(CHROOT)/home/$(MASH_USER)/install.sh"
 
 
+# .ONESHELL:
 #: Send new downloads to the chroot environment (if one is active) AND
 #: do the same in reverse, only adding files (no deletion).
-sync-downloads:
-	@if ! ./4make/chroot-status.sh; then \
-		CHROOT_DOWNLOAD_DIR="$(CHROOT)/home/$(MASH_USER)/.cache/mash/downloads" \
-		;sudo mkdir -p "$${CHROOT_DOWNLOAD_DIR}" \
-		;sudo chown "$(MASH_UID):$(MASH_UID)" "$${CHROOT_DOWNLOAD_DIR}" \
-		;sudo rsync "$(RSYNC_OPTS)" "$(DOWNLOAD_DIR)/" "$${CHROOT_DOWNLOAD_DIR}/" \
-		;sudo rsync "$(RSYNC_OPTS)" "$${CHROOT_DOWNLOAD_DIR}/" "$(DOWNLOAD_DIR)/" \
-		;sudo chown -R "$(MASH_UID):$(MASH_UID)" "$${CHROOT_DOWNLOAD_DIR}" \
-		;sudo chown -R "$(USER):$(USER)" "$(DOWNLOAD_DIR)/" \
-	;fi
-	@# No need to say anything as chroot-status.sh explains it all ;)
+sync-downloads: CHROOT_DOWNLOAD_DIR= $(CHROOT)/home/$(MASH_USER)/.cache/mash/downloads
+sync-downloads:  _ensure_chroot
+	CHROOT_DOWNLOAD_DIR="$(CHROOT)/home/$(MASH_USER)/.cache/mash/downloads"
+	sudo mkdir -p "$${CHROOT_DOWNLOAD_DIR}" || exit 11
+	sudo chown "$(MASH_UID):$(MASH_UID)" "$${CHROOT_DOWNLOAD_DIR}"  || exit 12
+	sudo rsync "$(RSYNC_OPTS)" "$(DOWNLOAD_DIR)/" "$${CHROOT_DOWNLOAD_DIR}/" || exit 13
+	sudo rsync "$(RSYNC_OPTS)" "$${CHROOT_DOWNLOAD_DIR}/" "$(DOWNLOAD_DIR)/" || exit 14
+	sudo chown -R "$(MASH_UID):$(MASH_UID)" "$${CHROOT_DOWNLOAD_DIR}"
+	sudo chown -R "$(USER):$(USER)" "$(DOWNLOAD_DIR)/"
+
+
+clean-tarballs:
+	rm -rf $(BUILD_DIR); mkdir -p $(BUILD_DIR)
+
+
+clean-downloads:
+	rm -rf $(DOWNLOAD_DIR); mkdir -p $(DOWNLOAD_DIR)
+
+
+clean:  clean-tarballs
+
+
+clean-all: clean-tarballs clean-downloads
 
 
 #: Dump chroot status and return a crafted rc (see the script [1] for detials).
 #: [1] ./4make/chroot-status.sh
 status:
-	@if ./4make/chroot-status.sh; then echo "rc=$$?"; else echo "rc=$$?"; fi
+	@./4make/chroot-status.sh && echo "(rc=$$?)" || echo "(rc=$$?)"
 
 
-.PHONY:  umount-chroot prep-chroot-dir mount-chroot chroot-down
+.PHONY:  _ensure_chroot _ensure_no_chroot mount-chroot umount-chroot prep-chroot-dir chroot-down
+.PHONY:  clean-tarballs clean-downloads clean-all clean
 .PHONY:  headless-up headless-down mate-desktop-up mate-desktop-down
-.PHONY:  clean-tarballs clean-mash-timestamp clean-all clean
-.PHONY:  sync-mash-forced sync-downloads status
+.PHONY:  sync-mash sync-downloads status
